### ISSUE TITLE
If you specify gzip on files but not in the options, headers aren't set

### ISSUE THREAD

**Issue by Bockit** [smallmultiples/grunt-s3-sync#8]
```
s3Sync =
    options:
        concurrency: 30
        db: -> s3Cache
        key: '<%= my-key %>'
        secret: '<%= my-secret %>'
        bucket: 'my-bucket'
        region: 'my-region'
        gzip: true
    stage:
        files: [{
            root: __dirname + '/build/stage'
            src: 'build/stage/**'
            dest: '/'
        }]
    production:
        files: [{
            root: __dirname + '/build/prod'
            src: 'build/prod/**'
            dest: '/'
        }]
```

So if you run with this config, files are gzipped correctly, but when served they come down without the gzip headers.

Looking through the code this seems to be because the stream is created and used with the options from the overall options, and then per-file it overrides them for gzipping, but doesn't change the headers.
